import { Client } from "pg";

import { acceptanceNamespace, stableAcceptanceErrorCode } from "./contracts";
import { writeAcceptanceArtifact } from "./output";
import { assertPostBrowserPrerequisites } from "./prerequisites";

type Check = Readonly<{ code: string; status: "PASS" | "FAIL" }>;

function required(name: string): string { const value = process.env[name]?.trim(); if (!value) throw new Error(`${name}_REQUIRED`); return value; }

async function main(): Promise<void> {
  const marker = required("STAGING_RUN_MARKER");
  await assertPostBrowserPrerequisites(process.env);
  const namespace = acceptanceNamespace(marker);
  const client = new Client({ connectionString: required("DIRECT_URL") });
  const checks: Check[] = [];
  await client.connect();
  try {
    await client.query("BEGIN READ ONLY");
    const classroom = await client.query<{ count: string }>("SELECT count(*)::text AS count FROM classrooms c JOIN app_users manager ON manager.id = c.manager_id JOIN classroom_memberships m ON m.classroom_id = c.id JOIN app_users student ON student.id = m.student_id WHERE c.id = $1::uuid AND c.name = $2 AND manager.auth_subject = $3 AND m.ended_at IS NULL AND student.auth_subject IN ($4, $5) HAVING count(*) = 2 AND count(DISTINCT student.auth_subject) = 2", [namespace.classroomId, namespace.classroomName, required("STAGING_TEST_TEACHER_CLERK_ID"), required("STAGING_TEST_STUDENT_CLERK_ID"), required("STAGING_TEST_OTHER_STUDENT_CLERK_ID")]);
    const allMemberships = await client.query<{ count: string }>("SELECT count(*)::text AS count FROM classroom_memberships WHERE classroom_id = $1::uuid", [namespace.classroomId]);
    checks.push({ code: "NAMESPACE_CLASSROOM_AND_MEMBERSHIPS_EXACT", status: classroom.rows[0]?.count === "2" && allMemberships.rows[0]?.count === "3" ? "PASS" : "FAIL" });
    const membershipHistory = await client.query<{ interval_count: string; ended_count: string; current_count: string; executed_intents: string; succeeded_audits: string }>("SELECT count(DISTINCT m.id)::text AS interval_count, count(DISTINCT m.id) FILTER (WHERE m.ended_at IS NOT NULL)::text AS ended_count, count(DISTINCT m.id) FILTER (WHERE m.ended_at IS NULL)::text AS current_count, count(DISTINCT ai.id) FILTER (WHERE ai.status = 'EXECUTED' AND ai.action_name = 'apply_classroom_membership_change')::text AS executed_intents, count(DISTINCT audit.id) FILTER (WHERE audit.outcome = 'SUCCEEDED' AND audit.action_name = 'apply_classroom_membership_change')::text AS succeeded_audits FROM classrooms c JOIN classroom_memberships m ON m.classroom_id = c.id JOIN app_users student ON student.id = m.student_id LEFT JOIN action_intents ai ON ai.target_id = c.id LEFT JOIN action_audits audit ON audit.action_intent_id = ai.id WHERE c.id = $1::uuid AND student.auth_subject = $2", [namespace.classroomId, required("STAGING_TEST_OTHER_STUDENT_CLERK_ID")]);
    const membershipHistoryRow = membershipHistory.rows[0];
    checks.push({ code: "MEMBERSHIP_HISTORY_INTENTS_AND_AUDITS_EXACT", status: membershipHistoryRow?.interval_count === "2" && membershipHistoryRow.ended_count === "1" && membershipHistoryRow.current_count === "1" && membershipHistoryRow.executed_intents === "2" && membershipHistoryRow.succeeded_audits === "2" ? "PASS" : "FAIL" });
    const loop = await client.query<{ draft_count: string; release_count: string; submission_count: string; primary_submission_count: string; revision_count: string; feedback_count: string; closed_count: string; manual_count: string }>("SELECT count(DISTINCT d.id)::text AS draft_count, count(DISTINCT r.id)::text AS release_count, count(DISTINCT s.id)::text AS submission_count, count(DISTINCT s.id) FILTER (WHERE submission_student.auth_subject = $4)::text AS primary_submission_count, count(DISTINCT sr.id)::text AS revision_count, count(DISTINCT fr.id)::text AS feedback_count, count(DISTINCT r.id) FILTER (WHERE r.status = 'CLOSED')::text AS closed_count, count(DISTINCT dr.id) FILTER (WHERE dr.source = 'MANUAL' AND dr.agent_run_id IS NULL)::text AS manual_count FROM activity_drafts d LEFT JOIN activity_draft_revisions dr ON dr.draft_id = d.id LEFT JOIN activity_releases r ON r.source_draft_id = d.id AND r.classroom_id = $1::uuid LEFT JOIN submissions s ON s.release_id = r.id LEFT JOIN app_users submission_student ON submission_student.id = s.student_id LEFT JOIN submission_revisions sr ON sr.submission_id = s.id LEFT JOIN teacher_feedback f ON f.submission_revision_id = sr.id LEFT JOIN teacher_feedback_revisions fr ON fr.teacher_feedback_id = f.id WHERE d.title = $2 AND d.owner_id = (SELECT id FROM app_users WHERE auth_subject = $3)", [namespace.classroomId, namespace.activityTitle, required("STAGING_TEST_TEACHER_CLERK_ID"), required("STAGING_TEST_STUDENT_CLERK_ID")]);
    const row = loop.rows[0];
    checks.push({ code: "MANUAL_DRAFT_RELEASE_SUBMISSION_FEEDBACK_CLOSED", status: row && row.draft_count === "1" && row.release_count === "1" && row.submission_count === "1" && row.primary_submission_count === "1" && row.revision_count === "1" && row.feedback_count === "1" && row.closed_count === "1" && row.manual_count === "1" ? "PASS" : "FAIL" });
    const attachment = await client.query<{ attachment_count: string; ready_count: string; formal_link_count: string }>("WITH target AS (SELECT r.id AS release_id FROM activity_drafts d JOIN activity_releases r ON r.source_draft_id = d.id WHERE d.title = $2 AND d.owner_id = (SELECT id FROM app_users WHERE auth_subject = $3) AND r.classroom_id = $1::uuid) SELECT count(DISTINCT attachment.id)::text AS attachment_count, count(DISTINCT attachment.id) FILTER (WHERE attachment.status = 'READY' AND attachment.original_filename = $5)::text AS ready_count, count(DISTINCT (revision_attachment.submission_revision_id, revision_attachment.attachment_id)) FILTER (WHERE revision.id IS NOT NULL)::text AS formal_link_count FROM target JOIN submissions AS submission ON submission.release_id = target.release_id JOIN app_users AS student ON student.id = submission.student_id LEFT JOIN submission_attachments AS attachment ON attachment.submission_id = submission.id LEFT JOIN submission_revision_attachments AS revision_attachment ON revision_attachment.attachment_id = attachment.id LEFT JOIN submission_revisions AS revision ON revision.id = revision_attachment.submission_revision_id AND revision.submission_id = submission.id WHERE student.auth_subject = $4", [namespace.classroomId, namespace.activityTitle, required("STAGING_TEST_TEACHER_CLERK_ID"), required("STAGING_TEST_STUDENT_CLERK_ID"), `synthetic-${marker}.png`]);
    const attachmentRow = attachment.rows[0];
    checks.push({ code: "PRIVATE_ATTACHMENT_READY_AND_FORMALIZED", status: attachmentRow?.attachment_count === "1" && attachmentRow.ready_count === "1" && attachmentRow.formal_link_count === "1" ? "PASS" : "FAIL" });
    const history = await client.query<{ snapshot_count: string; executed_intents: string; publish_close_audits: string; feedback_audits: string; stale_close_audits: string }>("WITH target AS (SELECT d.id AS draft_id, r.id AS release_id, r.action_intent_id, r.close_action_intent_id FROM activity_drafts d JOIN activity_releases r ON r.source_draft_id = d.id WHERE d.title = $2 AND d.owner_id = (SELECT id FROM app_users WHERE auth_subject = $3) AND r.classroom_id = $1::uuid), feedback_intents AS (SELECT fr.action_intent_id FROM target t JOIN submissions s ON s.release_id = t.release_id JOIN submission_revisions sr ON sr.submission_id = s.id JOIN teacher_feedback f ON f.submission_revision_id = sr.id JOIN teacher_feedback_revisions fr ON fr.teacher_feedback_id = f.id WHERE sr.text_evidence = $4 AND fr.body = $5 AND fr.source = 'MANUAL' AND fr.agent_run_id IS NULL) SELECT count(DISTINCT snap.release_id) FILTER (WHERE snap.source_draft_version = 1 AND snap.content->>'title' = $2)::text AS snapshot_count, count(DISTINCT ai.id) FILTER (WHERE ai.status = 'EXECUTED' AND ai.agent_run_id IS NULL AND ai.action_name IN ('publish_activity_release', 'close_activity_release', 'save_teacher_feedback'))::text AS executed_intents, count(DISTINCT audit.id) FILTER (WHERE audit.outcome = 'SUCCEEDED' AND audit.action_name IN ('publish_activity_release', 'close_activity_release'))::text AS publish_close_audits, count(DISTINCT feedback_audit.id) FILTER (WHERE feedback_audit.outcome = 'SUCCEEDED' AND feedback_audit.action_name = 'save_teacher_feedback')::text AS feedback_audits, count(DISTINCT stale_audit.id) FILTER (WHERE stale_audit.outcome = 'CONFLICTED' AND stale_audit.error_code = 'RELEASE_NOT_ACTIVE' AND stale_audit.action_name = 'save_submission_working_copy')::text AS stale_close_audits FROM target t LEFT JOIN activity_release_snapshots snap ON snap.release_id = t.release_id LEFT JOIN action_intents ai ON ai.id IN (t.action_intent_id, t.close_action_intent_id) OR ai.id IN (SELECT action_intent_id FROM feedback_intents) LEFT JOIN action_audits audit ON audit.action_intent_id IN (t.action_intent_id, t.close_action_intent_id) LEFT JOIN action_audits feedback_audit ON feedback_audit.action_intent_id IN (SELECT action_intent_id FROM feedback_intents) LEFT JOIN action_audits stale_audit ON stale_audit.target_id = t.release_id", [namespace.classroomId, namespace.activityTitle, required("STAGING_TEST_TEACHER_CLERK_ID"), namespace.evidenceText, namespace.feedbackText]);
    const historyRow = history.rows[0];
    checks.push({ code: "SNAPSHOT_INTENTS_AUDITS_AND_STALE_CLOSE_REJECTION", status: historyRow && historyRow.snapshot_count === "1" && historyRow.executed_intents === "3" && historyRow.publish_close_audits === "2" && historyRow.feedback_audits === "1" && historyRow.stale_close_audits === "1" ? "PASS" : "FAIL" });
    const otherHistory = await client.query<{ submission_count: string; revision_count: string; feedback_count: string }>("WITH target AS (SELECT r.id AS release_id FROM activity_drafts d JOIN activity_releases r ON r.source_draft_id = d.id WHERE d.title = $2 AND d.owner_id = (SELECT id FROM app_users WHERE auth_subject = $3) AND r.classroom_id = $1::uuid), other AS (SELECT id FROM app_users WHERE auth_subject = $4) SELECT count(DISTINCT s.id)::text AS submission_count, count(DISTINCT sr.id)::text AS revision_count, count(DISTINCT fr.id)::text AS feedback_count FROM target t CROSS JOIN other o LEFT JOIN submissions s ON s.release_id = t.release_id AND s.student_id = o.id LEFT JOIN submission_revisions sr ON sr.submission_id = s.id LEFT JOIN teacher_feedback f ON f.submission_revision_id = sr.id LEFT JOIN teacher_feedback_revisions fr ON fr.teacher_feedback_id = f.id", [namespace.classroomId, namespace.activityTitle, required("STAGING_TEST_TEACHER_CLERK_ID"), required("STAGING_TEST_OTHER_STUDENT_CLERK_ID")]);
    const otherHistoryRow = otherHistory.rows[0];
    checks.push({ code: "OTHER_STUDENT_HAS_NO_SUBMISSION_HISTORY", status: otherHistoryRow?.submission_count === "0" && otherHistoryRow.revision_count === "0" && otherHistoryRow.feedback_count === "0" ? "PASS" : "FAIL" });
    await client.query("ROLLBACK");
  } catch (error) {
    await client.query("ROLLBACK").catch(() => undefined);
    throw error;
  } finally { await client.end(); }
  const status = checks.every((item) => item.status === "PASS") ? "PASS" : "FAIL";
  await writeAcceptanceArtifact(marker, "verify.json", { schema: "staging-synthetic-acceptance-verify.v1", status, checks, readOnlyTransaction: true, realStudentDataAllowed: false, productionDecision: "NO_GO" });
  process.stdout.write(`${JSON.stringify({ schema: "staging-synthetic-acceptance-verify.v1", status })}\n`);
  if (status !== "PASS") process.exitCode = 1;
}

void main().catch(async (error: unknown) => {
  const marker = process.env.STAGING_RUN_MARKER?.trim() ?? "";
  try { await writeAcceptanceArtifact(marker, "verify.json", { schema: "staging-synthetic-acceptance-verify.v1", status: "FAIL", checks: [{ code: stableAcceptanceErrorCode(error), status: "FAIL" }], readOnlyTransaction: true, realStudentDataAllowed: false, productionDecision: "NO_GO" }); } catch { /* no output outside safe namespace */ }
  process.stdout.write(`{"schema":"staging-synthetic-acceptance-verify.v1","status":"FAIL","code":"${stableAcceptanceErrorCode(error)}"}\n`);
  process.exitCode = 1;
});
