import nextEnvironment from "@next/env";
import { bootstrapAdditionalClerkClassroomStudent, bootstrapClerkClassroom, bootstrapStandaloneClerkTeacher } from "../../../src/server/bootstrap/bootstrap-clerk-classroom";
import { createDatabaseClient } from "../../../src/server/db/client";
import { agentAcceptanceNamespace, agentAcceptanceOtherStudentDisplayName, agentAcceptanceOtherTeacherDisplayName, agentAcceptanceStudentDisplayName, agentAcceptanceTeacherDisplayName, evaluateAgentAcceptanceReadiness, stableAgentAcceptanceError } from "./contracts";
import { assertNoAgentBusinessHistory, probeAgentNamespace } from "./fixture";
import { writeAgentArtifact } from "./output";
import { assertAgentBootstrapPrerequisites } from "./prerequisites";
const required=(key:string)=>{const value=process.env[key]?.trim();if(!value)throw new Error(`${key}_REQUIRED`);return value;};
async function main(){nextEnvironment.loadEnvConfig(process.cwd());const marker=required("STAGING_RUN_MARKER");if(evaluateAgentAcceptanceReadiness(process.env).status!=="PASS")throw new Error("STAGING_AGENT_ACCEPTANCE_READINESS_FAILED");await assertAgentBootstrapPrerequisites(process.env);const ns=agentAcceptanceNamespace(marker);const db=createDatabaseClient(required("DIRECT_URL"));try{await assertNoAgentBusinessHistory(db,required("STAGING_TEST_TEACHER_CLERK_ID"),ns.activityTitle);const probe=await probeAgentNamespace(db,ns.classroomId,ns.classroomName,required("STAGING_TEST_TEACHER_CLERK_ID"),required("STAGING_TEST_STUDENT_CLERK_ID"),required("STAGING_TEST_OTHER_STUDENT_CLERK_ID"));if(probe==="COLLISION")throw new Error("STAGING_AGENT_ACCEPTANCE_NAMESPACE_COLLISION");const result=await bootstrapClerkClassroom(db,{teacherAuthSubject:required("STAGING_TEST_TEACHER_CLERK_ID"),teacherDisplayName:agentAcceptanceTeacherDisplayName,studentAuthSubject:required("STAGING_TEST_STUDENT_CLERK_ID"),studentDisplayName:agentAcceptanceStudentDisplayName,classroomId:ns.classroomId,classroomName:ns.classroomName});const otherStudent=await bootstrapAdditionalClerkClassroomStudent(db,{teacherAuthSubject:required("STAGING_TEST_TEACHER_CLERK_ID"),classroomId:ns.classroomId,classroomName:ns.classroomName,additionalStudentAuthSubject:required("STAGING_TEST_OTHER_STUDENT_CLERK_ID"),additionalStudentDisplayName:agentAcceptanceOtherStudentDisplayName});const otherTeacher=await bootstrapStandaloneClerkTeacher(db,{teacherAuthSubject:required("STAGING_TEST_OTHER_TEACHER_CLERK_ID"),teacherDisplayName:agentAcceptanceOtherTeacherDisplayName});await writeAgentArtifact(marker,"bootstrap.json",{schema:"staging-agent-acceptance-bootstrap.v1",status:"PASS",namespace:{marker,classroomDerived:true},collisionProbe:probe,resources:{teacher:result.teacher.status,student:result.student.status,otherStudent:otherStudent.additionalStudent.status,otherTeacher:otherTeacher.teacher.status,classroom:result.classroom.status,membership:result.membership.status,otherMembership:otherStudent.membership.status},realStudentDataAllowed:false,productionDecision:"NO_GO"});process.stdout.write('{"schema":"staging-agent-acceptance-bootstrap.v1","status":"PASS"}\n');}finally{await db.$disconnect();}}
void main().catch(async error=>{try{await writeAgentArtifact(process.env.STAGING_RUN_MARKER?.trim()??"","bootstrap.json",{schema:"staging-agent-acceptance-bootstrap.v1",status:"FAIL",checks:[{code:stableAgentAcceptanceError(error),status:"FAIL"}],realStudentDataAllowed:false,productionDecision:"NO_GO"});}catch{}process.stdout.write('{"schema":"staging-agent-acceptance-bootstrap.v1","status":"FAIL"}\n');process.exitCode=1;});
