import { createHmac, timingSafeEqual } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { isStagingDecision } from "../decision";
import { safeStagingRunDirectory } from "../output";
import { createSourceFingerprint } from "../source-fingerprint";
import { agentAcceptanceAttestations, evaluateAgentAcceptanceReadiness, type AgentAcceptanceEnvironment } from "./contracts";
import { writeAgentArtifact } from "./output";

const text = (e: AgentAcceptanceEnvironment, key: string) => e[key]?.trim() ?? "";
const fields = ["STAGING_RUN_MARKER", "GITHUB_RUN_ID", "GITHUB_RUN_ATTEMPT", "CDAS_DEPLOYMENT_ID", "CDAS_SOURCE_FINGERPRINT", "DATABASE_URL", "DIRECT_URL", "STAGING_DATABASE_NAME", "STAGING_BASE_URL", "STAGING_VERCEL_PROJECT_NAME", "STAGING_DEPLOYMENT_PROTECTION_REQUIRED", "STAGING_VERCEL_AUTOMATION_BYPASS_SECRET", "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY", "CLERK_SECRET_KEY", "STAGING_TEST_TEACHER_CLERK_ID", "STAGING_TEST_STUDENT_CLERK_ID", "STAGING_TEST_OTHER_STUDENT_CLERK_ID", "STAGING_TEST_OTHER_TEACHER_CLERK_ID", "AI_PROVIDER_DISABLED", "DEEPSEEK_API_KEY", "AI_MODEL", "AI_TOOL_APPROVAL_SECRET", "STAGING_ACCEPTANCE_TEST_TEACHER_NAME", "STAGING_ACCEPTANCE_TEST_STUDENT_NAME", "STAGING_ACCEPTANCE_TEST_OTHER_STUDENT_NAME", "STAGING_ACCEPTANCE_TEST_OTHER_TEACHER_NAME", ...agentAcceptanceAttestations] as const;
function mac(e: AgentAcceptanceEnvironment) { const secret = text(e, "STAGING_HEALTH_PROOF_SECRET"); if (Buffer.byteLength(secret, "utf8") < 32 || Buffer.byteLength(secret, "utf8") > 4096) return undefined; const canonical = fields.map((key) => `${key.length}:${key}=${Buffer.byteLength(text(e, key), "utf8")}:${text(e, key)}`).join("\n"); return createHmac("sha256", secret).update("cdas-staging-agent-acceptance-binding-v1\0", "utf8").update(canonical, "utf8").digest("hex"); }
export type AgentGate = Readonly<{ schema: "staging-agent-acceptance-gate.v1"; decision: "GO" | "NO_GO"; marker: string; githubRunId: string; githubRunAttempt: string; deploymentId: string; sourceFingerprint: string; bindingMac: string; checks: readonly { code: string; status: "PASS" | "FAIL" }[]; realStudentDataAllowed: false; productionDecision: "NO_GO" }>;
export async function createAgentGate(e: AgentAcceptanceEnvironment, decision: unknown): Promise<AgentGate> { const readiness = evaluateAgentAcceptanceReadiness(e); const fingerprint = createSourceFingerprint(); const binding = mac(e); const checks = [
  { code: "SAME_RUN_STAGING_GO", status: isStagingDecision(decision) && decision.decision === "GO" ? "PASS" as const : "FAIL" as const },
  { code: "AGENT_READINESS", status: readiness.status === "PASS" ? "PASS" as const : "FAIL" as const },
  { code: "SOURCE_FINGERPRINT", status: fingerprint === text(e, "CDAS_SOURCE_FINGERPRINT") ? "PASS" as const : "FAIL" as const },
  { code: "AGENT_BINDING_MAC", status: binding ? "PASS" as const : "FAIL" as const },
]; return { schema: "staging-agent-acceptance-gate.v1", decision: checks.every((item) => item.status === "PASS") ? "GO" : "NO_GO", marker: text(e,"STAGING_RUN_MARKER"), githubRunId: text(e,"GITHUB_RUN_ID"), githubRunAttempt: text(e,"GITHUB_RUN_ATTEMPT"), deploymentId:text(e,"CDAS_DEPLOYMENT_ID"), sourceFingerprint:fingerprint, bindingMac:binding ?? "", checks, realStudentDataAllowed:false, productionDecision:"NO_GO" }; }
export function isAgentGate(value: unknown, e: AgentAcceptanceEnvironment): value is AgentGate { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const x = value as Record<string, unknown>; const keys=["schema","decision","marker","githubRunId","githubRunAttempt","deploymentId","sourceFingerprint","bindingMac","checks","realStudentDataAllowed","productionDecision"]; const expected=mac(e); if (Object.keys(x).length !== keys.length || !keys.every(k=>k in x) || x.schema!=="staging-agent-acceptance-gate.v1" || x.decision!=="GO" || x.marker!==text(e,"STAGING_RUN_MARKER") || x.githubRunId!==text(e,"GITHUB_RUN_ID") || x.githubRunAttempt!==text(e,"GITHUB_RUN_ATTEMPT") || x.deploymentId!==text(e,"CDAS_DEPLOYMENT_ID") || x.sourceFingerprint!==text(e,"CDAS_SOURCE_FINGERPRINT") || x.realStudentDataAllowed!==false || x.productionDecision!=="NO_GO" || typeof x.bindingMac!=="string" || !expected || !/^[a-f0-9]{64}$/u.test(x.bindingMac)) return false; if (!timingSafeEqual(Buffer.from(x.bindingMac,"hex"),Buffer.from(expected,"hex")) || !Array.isArray(x.checks)) return false; const codes=["SAME_RUN_STAGING_GO","AGENT_READINESS","SOURCE_FINGERPRINT","AGENT_BINDING_MAC"]; return x.checks.length===codes.length && new Set(x.checks.map(c=>c && typeof c==="object"?(c as Record<string,unknown>).code:"")).size===codes.length && x.checks.every(c=>c && typeof c==="object" && Object.keys(c).length===2 && codes.includes((c as Record<string,unknown>).code as string) && (c as Record<string,unknown>).status==="PASS"); }
async function main() { const marker=text(process.env,"STAGING_RUN_MARKER"); let decision:unknown; try { decision=JSON.parse(await readFile(path.join(safeStagingRunDirectory(marker),"decision.json"),"utf8")); } catch { decision=undefined; } const gate=await createAgentGate(process.env,decision); await writeAgentArtifact(marker,"readiness.json",evaluateAgentAcceptanceReadiness(process.env)); await writeAgentArtifact(marker,"gate.json",gate); process.stdout.write(`${JSON.stringify({schema:gate.schema,decision:gate.decision})}\n`); if(gate.decision!=="GO") process.exitCode=1; }
if (process.argv[1] && import.meta.url===pathToFileURL(process.argv[1]).href) void main().catch(()=>{process.stdout.write('{"schema":"staging-agent-acceptance-gate.v1","decision":"NO_GO"}\n');process.exitCode=1;});
